services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: microservice-app
    restart: unless-stopped
    ports:
      # Optional: Only needed if not running behind a reverse proxy in the same Docker network
      - "3000:3000"
    env_file:
      - .env
